// todo-list
export const ADD_TODO = 'ADD_TODO'
export const REMVOVE_TODO = 'REMVOVE_TODO'
export const CHECK_ITEM_TODO = 'CHECK_ITEM_TODO'
export const CHECK_ALL_TODO = 'CHECK_ALL_TODO'
export const CLEAR_COMPLETED_TODO = 'CLEAR_COMPLETED_TODO'
export const FINISH_EDIT_TODO = 'FINISH_EDIT_TODO'
export const FILTER_TODOS = 'FILTER_TODOS'
